# OpenSportsSchema — https://github.com/sweatstack/open-sports-schema

version: "0.1.0"

sports:

  - code: cycling
    label: cycling

  - code: cycling.cyclocross
    label: cyclocross

  - code: cycling.gravel
    label: gravel cycling

  - code: cycling.mountain
    label: mountain biking

  - code: cycling.road
    label: road cycling

  - code: cycling.time_trial
    label: time trial cycling

  - code: cycling.track
    label: track cycling

  - code: generic
    label: generic

  - code: rowing
    label: rowing

  - code: running
    label: running

  - code: running.road
    label: road running

  - code: running.track
    label: track running

  - code: running.trail
    label: trail running

  - code: swimming
    label: swimming

  - code: swimming.open_water
    label: open water swimming

  - code: swimming.pool
    label: pool swimming

  - code: walking
    label: walking

  - code: walking.hiking
    label: hiking

  - code: xc_skiing
    label: XC skiing

  - code: xc_skiing.backcountry
    label: backcountry XC skiing

  - code: xc_skiing.classic
    label: classic XC skiing

  - code: xc_skiing.roller
    label: roller skiing

  - code: xc_skiing.roller.classic
    label: classic roller skiing

  - code: xc_skiing.roller.skate
    label: skate roller skiing

  - code: xc_skiing.skate
    label: skate XC skiing

modifiers:

  - code: assisted
    label: assisted

  - code: commute
    group: purpose
    label: commute

  - code: race
    group: purpose
    label: race

  - code: stationary
    label: stationary

  - code: training
    group: purpose
    label: training

  - code: virtual
    label: virtual
