# OpenSportsSchema — https://github.com/sweatstack/open-sports-schema

version: "0.1.0"

sports:

  - code: cycling
    label: cycling

  - code: cycling.cyclocross
    label: cyclocross

  - code: cycling.road
    label: road cycling

  - code: cycling.track
    label: track cycling

  - code: generic
    label: generic

  - code: running
    label: running

  - code: running.road
    label: road running

  - code: running.track
    label: track running

  - code: running.trail
    label: trail running

  - code: xc_skiing
    label: XC skiing

  - code: xc_skiing.roller
    label: roller skiing

  - code: xc_skiing.roller.classic
    label: classic roller skiing

  - code: xc_skiing.roller.skate
    label: skate roller skiing

  - code: xc_skiing.backcountry
    label: backcountry XC skiing

  - code: xc_skiing.classic
    label: classic XC skiing

  - code: xc_skiing.skate
    label: skate XC skiing

modifiers:

  - code: commute
    group: purpose
    label: commute

  - code: race
    group: purpose
    label: race

  - code: training
    group: purpose
    label: training

  - code: stationary
    label: stationary

  - code: virtual
    label: virtual

  - code: assisted
    label: assisted

