from open_sport_taxonomy._platform import Platform
from open_sport_taxonomy._platforms import (
    GARMIN_TRAINING_API_ENTRIES_BY_TARGET,
    GARMIN_TRAINING_API_FALLBACK_DECODE,
    GARMIN_TRAINING_API_FALLBACK_ENCODE,
    GARMIN_TRAINING_API_PREFERRED_INDEX,
    GARMIN_TRAINING_API_TARGET_COARSENING,
)

garmin_training_api = Platform(
    entries_by_target=GARMIN_TRAINING_API_ENTRIES_BY_TARGET,
    preferred_index=GARMIN_TRAINING_API_PREFERRED_INDEX,
    fallback_encode=GARMIN_TRAINING_API_FALLBACK_ENCODE,
    fallback_decode=GARMIN_TRAINING_API_FALLBACK_DECODE,
    target_coarsening=GARMIN_TRAINING_API_TARGET_COARSENING,
)
