# Auto-generated from schema.yaml — do not edit.
# Run: uv run scripts/generate.py

from __future__ import annotations

from open_sport_taxonomy._platform import GarminFitCode
from open_sport_taxonomy._sport import Sport


# ---- apple_healthkit -----------------------------------------------------

APPLE_HEALTHKIT_FALLBACK_ENCODE = 3000
APPLE_HEALTHKIT_FALLBACK_DECODE: Sport = Sport('generic')

APPLE_HEALTHKIT_ENTRIES_BY_TARGET: dict = {
    1: (None, False),
    2: (None, False),
    3: (None, False),
    4: (None, False),
    5: (None, False),
    6: (None, False),
    7: (None, False),
    8: (None, False),
    9: (None, False),
    10: (None, False),
    11: (None, False),
    12: (None, False),
    13: (Sport('cycling'), True),
    14: (None, False),
    15: (None, False),
    16: (None, False),
    17: (None, False),
    18: (None, False),
    19: (None, False),
    20: (None, False),
    21: (None, False),
    22: (None, False),
    23: (None, False),
    24: (Sport('walking.hiking'), True),
    25: (None, False),
    26: (None, False),
    27: (None, False),
    28: (None, False),
    29: (None, False),
    30: (None, False),
    31: (None, False),
    32: (None, False),
    33: (None, False),
    34: (None, False),
    35: (Sport('rowing'), True),
    36: (None, False),
    37: (Sport('running'), True),
    38: (None, False),
    39: (None, False),
    40: (None, False),
    41: (None, False),
    42: (None, False),
    43: (None, False),
    44: (None, False),
    45: (None, False),
    46: (Sport('swimming'), True),
    47: (None, False),
    48: (None, False),
    49: (None, False),
    50: (None, False),
    51: (None, False),
    52: (Sport('walking'), True),
    53: (None, False),
    54: (None, False),
    55: (None, False),
    56: (None, False),
    57: (None, False),
    58: (None, False),
    59: (None, False),
    60: (Sport('xc_skiing'), True),
    61: (Sport('alpine_skiing'), True),
    62: (None, False),
    63: (None, False),
    64: (None, False),
    65: (None, False),
    66: (None, False),
    67: (Sport('snowboarding'), True),
    68: (None, False),
    69: (None, False),
    70: (None, False),
    71: (None, False),
    72: (None, False),
    73: (None, False),
    74: (Sport('hand_cycling'), True),
    75: (None, False),
    76: (None, False),
    77: (None, False),
    78: (None, False),
    79: (None, False),
    80: (None, False),
    82: (None, False),
    83: (None, False),
    84: (None, False),
    3000: (Sport('generic'), True),
}

APPLE_HEALTHKIT_PREFERRED_INDEX: dict = {
    ('cycling', frozenset()): 13,
    ('walking.hiking', frozenset()): 24,
    ('rowing', frozenset()): 35,
    ('running', frozenset()): 37,
    ('swimming', frozenset()): 46,
    ('walking', frozenset()): 52,
    ('xc_skiing', frozenset()): 60,
    ('alpine_skiing', frozenset()): 61,
    ('snowboarding', frozenset()): 67,
    ('hand_cycling', frozenset()): 74,
    ('generic', frozenset()): 3000,
}

APPLE_HEALTHKIT_TARGET_COARSENING: tuple = ()

# ---- garmin_fit ----------------------------------------------------------

GARMIN_FIT_FALLBACK_ENCODE = GarminFitCode(sport=0, sub_sport=0)
GARMIN_FIT_FALLBACK_DECODE: Sport = Sport('generic')

GARMIN_FIT_ENTRIES_BY_TARGET: dict = {
    GarminFitCode(sport=0, sub_sport=0): (Sport('generic'), True),
    GarminFitCode(sport=1, sub_sport=0): (Sport('running'), True),
    GarminFitCode(sport=1, sub_sport=1): (Sport('running+stationary'), True),
    GarminFitCode(sport=1, sub_sport=2): (Sport('running.road'), True),
    GarminFitCode(sport=1, sub_sport=3): (Sport('running.trail'), True),
    GarminFitCode(sport=1, sub_sport=4): (Sport('running.track'), True),
    GarminFitCode(sport=1, sub_sport=45): (None, False),
    GarminFitCode(sport=2, sub_sport=0): (Sport('cycling'), True),
    GarminFitCode(sport=2, sub_sport=5): (Sport('cycling+stationary'), False),
    GarminFitCode(sport=2, sub_sport=6): (Sport('cycling+stationary'), True),
    GarminFitCode(sport=2, sub_sport=7): (Sport('cycling.road'), True),
    GarminFitCode(sport=2, sub_sport=8): (Sport('cycling.mountain'), True),
    GarminFitCode(sport=2, sub_sport=9): (None, False),
    GarminFitCode(sport=2, sub_sport=10): (None, False),
    GarminFitCode(sport=2, sub_sport=11): (Sport('cycling.cyclocross'), True),
    GarminFitCode(sport=2, sub_sport=12): (Sport('hand_cycling'), True),
    GarminFitCode(sport=2, sub_sport=13): (Sport('cycling.track'), True),
    GarminFitCode(sport=2, sub_sport=29): (None, False),
    GarminFitCode(sport=2, sub_sport=46): (Sport('cycling.gravel'), True),
    GarminFitCode(sport=2, sub_sport=47): (None, False),
    GarminFitCode(sport=2, sub_sport=48): (None, False),
    GarminFitCode(sport=2, sub_sport=49): (None, False),
    GarminFitCode(sport=3, sub_sport=0): (None, False),
    GarminFitCode(sport=3, sub_sport=32): (None, False),
    GarminFitCode(sport=3, sub_sport=33): (None, False),
    GarminFitCode(sport=3, sub_sport=34): (None, False),
    GarminFitCode(sport=4, sub_sport=0): (None, False),
    GarminFitCode(sport=4, sub_sport=1): (Sport('running+stationary'), False),
    GarminFitCode(sport=4, sub_sport=6): (Sport('cycling+stationary'), False),
    GarminFitCode(sport=4, sub_sport=14): (Sport('rowing+stationary'), True),
    GarminFitCode(sport=4, sub_sport=15): (None, False),
    GarminFitCode(sport=4, sub_sport=16): (None, False),
    GarminFitCode(sport=4, sub_sport=25): (None, False),
    GarminFitCode(sport=4, sub_sport=27): (Sport('walking+stationary'), False),
    GarminFitCode(sport=4, sub_sport=44): (None, False),
    GarminFitCode(sport=5, sub_sport=0): (Sport('swimming'), True),
    GarminFitCode(sport=5, sub_sport=17): (Sport('swimming.pool'), True),
    GarminFitCode(sport=5, sub_sport=18): (Sport('swimming.open_water'), True),
    GarminFitCode(sport=6, sub_sport=0): (None, False),
    GarminFitCode(sport=7, sub_sport=0): (None, False),
    GarminFitCode(sport=8, sub_sport=0): (None, False),
    GarminFitCode(sport=8, sub_sport=21): (None, False),
    GarminFitCode(sport=8, sub_sport=22): (None, False),
    GarminFitCode(sport=8, sub_sport=23): (None, False),
    GarminFitCode(sport=9, sub_sport=0): (None, False),
    GarminFitCode(sport=10, sub_sport=0): (None, False),
    GarminFitCode(sport=10, sub_sport=19): (None, False),
    GarminFitCode(sport=10, sub_sport=20): (None, False),
    GarminFitCode(sport=10, sub_sport=26): (None, False),
    GarminFitCode(sport=10, sub_sport=43): (None, False),
    GarminFitCode(sport=11, sub_sport=0): (Sport('walking'), True),
    GarminFitCode(sport=11, sub_sport=27): (Sport('walking+stationary'), True),
    GarminFitCode(sport=11, sub_sport=30): (None, False),
    GarminFitCode(sport=11, sub_sport=31): (None, False),
    GarminFitCode(sport=12, sub_sport=0): (Sport('xc_skiing'), True),
    GarminFitCode(sport=12, sub_sport=42): (Sport('xc_skiing.skate'), True),
    GarminFitCode(sport=13, sub_sport=0): (Sport('alpine_skiing'), True),
    GarminFitCode(sport=13, sub_sport=37): (Sport('alpine_skiing'), False),
    GarminFitCode(sport=13, sub_sport=38): (Sport('alpine_skiing'), False),
    GarminFitCode(sport=14, sub_sport=0): (Sport('snowboarding'), True),
    GarminFitCode(sport=14, sub_sport=37): (Sport('snowboarding'), False),
    GarminFitCode(sport=14, sub_sport=38): (Sport('snowboarding'), False),
    GarminFitCode(sport=15, sub_sport=0): (Sport('rowing'), True),
    GarminFitCode(sport=16, sub_sport=0): (None, False),
    GarminFitCode(sport=17, sub_sport=0): (Sport('walking.hiking'), True),
    GarminFitCode(sport=18, sub_sport=0): (None, False),
    GarminFitCode(sport=19, sub_sport=0): (None, False),
    GarminFitCode(sport=20, sub_sport=0): (None, False),
    GarminFitCode(sport=20, sub_sport=39): (None, False),
    GarminFitCode(sport=20, sub_sport=40): (None, False),
    GarminFitCode(sport=20, sub_sport=110): (None, False),
    GarminFitCode(sport=20, sub_sport=111): (None, False),
    GarminFitCode(sport=20, sub_sport=112): (None, False),
    GarminFitCode(sport=20, sub_sport=113): (None, False),
    GarminFitCode(sport=20, sub_sport=114): (None, False),
    GarminFitCode(sport=20, sub_sport=115): (None, False),
    GarminFitCode(sport=20, sub_sport=116): (None, False),
    GarminFitCode(sport=20, sub_sport=117): (None, False),
    GarminFitCode(sport=20, sub_sport=118): (None, False),
    GarminFitCode(sport=20, sub_sport=119): (None, False),
    GarminFitCode(sport=21, sub_sport=0): (None, False),
    GarminFitCode(sport=21, sub_sport=28): (None, False),
    GarminFitCode(sport=22, sub_sport=0): (None, False),
    GarminFitCode(sport=22, sub_sport=35): (None, False),
    GarminFitCode(sport=22, sub_sport=36): (None, False),
    GarminFitCode(sport=23, sub_sport=0): (None, False),
    GarminFitCode(sport=24, sub_sport=0): (None, False),
    GarminFitCode(sport=25, sub_sport=0): (None, False),
    GarminFitCode(sport=26, sub_sport=0): (None, False),
    GarminFitCode(sport=27, sub_sport=0): (None, False),
    GarminFitCode(sport=28, sub_sport=0): (None, False),
    GarminFitCode(sport=29, sub_sport=0): (None, False),
    GarminFitCode(sport=30, sub_sport=0): (None, False),
    GarminFitCode(sport=31, sub_sport=0): (None, False),
    GarminFitCode(sport=32, sub_sport=0): (None, False),
    GarminFitCode(sport=32, sub_sport=65): (None, False),
    GarminFitCode(sport=33, sub_sport=0): (None, False),
    GarminFitCode(sport=34, sub_sport=0): (None, False),
    GarminFitCode(sport=35, sub_sport=0): (None, False),
    GarminFitCode(sport=36, sub_sport=0): (None, False),
    GarminFitCode(sport=37, sub_sport=0): (None, False),
    GarminFitCode(sport=38, sub_sport=0): (None, False),
    GarminFitCode(sport=39, sub_sport=0): (None, False),
    GarminFitCode(sport=40, sub_sport=0): (None, False),
    GarminFitCode(sport=41, sub_sport=0): (None, False),
    GarminFitCode(sport=41, sub_sport=41): (None, False),
    GarminFitCode(sport=42, sub_sport=0): (None, False),
    GarminFitCode(sport=42, sub_sport=41): (None, False),
    GarminFitCode(sport=43, sub_sport=0): (None, False),
    GarminFitCode(sport=44, sub_sport=0): (None, False),
    GarminFitCode(sport=45, sub_sport=0): (None, False),
    GarminFitCode(sport=46, sub_sport=0): (None, False),
    GarminFitCode(sport=47, sub_sport=0): (None, False),
    GarminFitCode(sport=48, sub_sport=0): (None, False),
    GarminFitCode(sport=49, sub_sport=0): (None, False),
    GarminFitCode(sport=53, sub_sport=0): (None, False),
    GarminFitCode(sport=53, sub_sport=53): (None, False),
    GarminFitCode(sport=53, sub_sport=54): (None, False),
    GarminFitCode(sport=53, sub_sport=55): (None, False),
    GarminFitCode(sport=53, sub_sport=56): (None, False),
    GarminFitCode(sport=53, sub_sport=57): (None, False),
    GarminFitCode(sport=62, sub_sport=0): (None, False),
    GarminFitCode(sport=62, sub_sport=73): (None, False),
    GarminFitCode(sport=62, sub_sport=74): (None, False),
    GarminFitCode(sport=62, sub_sport=75): (None, False),
    GarminFitCode(sport=64, sub_sport=0): (None, False),
    GarminFitCode(sport=64, sub_sport=84): (None, False),
    GarminFitCode(sport=64, sub_sport=85): (None, False),
    GarminFitCode(sport=65, sub_sport=0): (None, False),
    GarminFitCode(sport=66, sub_sport=0): (None, False),
    GarminFitCode(sport=67, sub_sport=0): (None, False),
    GarminFitCode(sport=69, sub_sport=0): (None, False),
    GarminFitCode(sport=71, sub_sport=0): (None, False),
    GarminFitCode(sport=72, sub_sport=0): (None, False),
    GarminFitCode(sport=73, sub_sport=0): (None, False),
    GarminFitCode(sport=74, sub_sport=0): (None, False),
    GarminFitCode(sport=75, sub_sport=0): (None, False),
    GarminFitCode(sport=76, sub_sport=0): (None, False),
    GarminFitCode(sport=77, sub_sport=0): (None, False),
    GarminFitCode(sport=80, sub_sport=0): (None, False),
    GarminFitCode(sport=82, sub_sport=0): (None, False),
    GarminFitCode(sport=83, sub_sport=0): (None, False),
    GarminFitCode(sport=84, sub_sport=0): (None, False),
}

GARMIN_FIT_PREFERRED_INDEX: dict = {
    ('generic', frozenset()): GarminFitCode(sport=0, sub_sport=0),
    ('running', frozenset()): GarminFitCode(sport=1, sub_sport=0),
    ('running', frozenset({'stationary'})): GarminFitCode(sport=1, sub_sport=1),
    ('running.road', frozenset()): GarminFitCode(sport=1, sub_sport=2),
    ('running.trail', frozenset()): GarminFitCode(sport=1, sub_sport=3),
    ('running.track', frozenset()): GarminFitCode(sport=1, sub_sport=4),
    ('cycling', frozenset()): GarminFitCode(sport=2, sub_sport=0),
    ('cycling', frozenset({'stationary'})): GarminFitCode(sport=2, sub_sport=6),
    ('cycling.road', frozenset()): GarminFitCode(sport=2, sub_sport=7),
    ('cycling.mountain', frozenset()): GarminFitCode(sport=2, sub_sport=8),
    ('cycling.cyclocross', frozenset()): GarminFitCode(sport=2, sub_sport=11),
    ('hand_cycling', frozenset()): GarminFitCode(sport=2, sub_sport=12),
    ('cycling.track', frozenset()): GarminFitCode(sport=2, sub_sport=13),
    ('cycling.gravel', frozenset()): GarminFitCode(sport=2, sub_sport=46),
    ('rowing', frozenset({'stationary'})): GarminFitCode(sport=4, sub_sport=14),
    ('swimming', frozenset()): GarminFitCode(sport=5, sub_sport=0),
    ('swimming.pool', frozenset()): GarminFitCode(sport=5, sub_sport=17),
    ('swimming.open_water', frozenset()): GarminFitCode(sport=5, sub_sport=18),
    ('walking', frozenset()): GarminFitCode(sport=11, sub_sport=0),
    ('walking', frozenset({'stationary'})): GarminFitCode(sport=11, sub_sport=27),
    ('xc_skiing', frozenset()): GarminFitCode(sport=12, sub_sport=0),
    ('xc_skiing.skate', frozenset()): GarminFitCode(sport=12, sub_sport=42),
    ('alpine_skiing', frozenset()): GarminFitCode(sport=13, sub_sport=0),
    ('snowboarding', frozenset()): GarminFitCode(sport=14, sub_sport=0),
    ('rowing', frozenset()): GarminFitCode(sport=15, sub_sport=0),
    ('walking.hiking', frozenset()): GarminFitCode(sport=17, sub_sport=0),
}

GARMIN_FIT_TARGET_COARSENING: tuple = ({"reset": {'sub_sport': 0}}, {"reset": {'sport': 0, 'sub_sport': 0}},)

# ---- garmin_training_api -------------------------------------------------

GARMIN_TRAINING_API_FALLBACK_ENCODE = 'GENERIC'
GARMIN_TRAINING_API_FALLBACK_DECODE: Sport = Sport('generic')

GARMIN_TRAINING_API_ENTRIES_BY_TARGET: dict = {
    'CARDIO_TRAINING': (None, False),
    'CYCLING': (Sport('cycling'), True),
    'GENERIC': (Sport('generic'), True),
    'LAP_SWIMMING': (Sport('swimming'), True),
    'MULTI_SPORT': (None, False),
    'PILATES': (None, False),
    'RUNNING': (Sport('running'), True),
    'STRENGTH_TRAINING': (None, False),
    'YOGA': (None, False),
}

GARMIN_TRAINING_API_PREFERRED_INDEX: dict = {
    ('cycling', frozenset()): 'CYCLING',
    ('generic', frozenset()): 'GENERIC',
    ('swimming', frozenset()): 'LAP_SWIMMING',
    ('running', frozenset()): 'RUNNING',
}

GARMIN_TRAINING_API_TARGET_COARSENING: tuple = ()

# ---- polar ---------------------------------------------------------------

POLAR_FALLBACK_ENCODE = 'OTHER_OUTDOOR'
POLAR_FALLBACK_DECODE: Sport = Sport('generic')

POLAR_ENTRIES_BY_TARGET: dict = {
    'AEROBICS': (None, False),
    'AGILITY': (None, False),
    'AMERICAN_FOOTBALL': (None, False),
    'AQUATICS': (None, False),
    'BACKCOUNTRY_SKIING': (Sport('alpine_skiing'), False),
    'BADMINTON': (None, False),
    'BALLET_DANCING': (None, False),
    'BALLROOM_DANCING': (None, False),
    'BASEBALL': (None, False),
    'BASKETBALL': (None, False),
    'BEACH_TENNIS': (None, False),
    'BEACH_VOLLEYBALL': (None, False),
    'BIATHLON': (None, False),
    'BODY_AND_MIND': (None, False),
    'BOOTCAMP': (None, False),
    'BOXING': (None, False),
    'CALISTHENICS': (None, False),
    'CIRCUIT_TRAINING': (None, False),
    'CLIMBING': (None, False),
    'CORE': (None, False),
    'CRICKET': (None, False),
    'CROSS-COUNTRY_SKIING': (Sport('xc_skiing'), True),
    'CROSS_COUNTRY_RUNNING': (Sport('running.trail'), False),
    'CROSS_TRAINER': (None, False),
    'CURLING': (None, False),
    'CYCLING': (Sport('cycling'), True),
    'DANCING': (None, False),
    'DOWNHILL_SKIING': (Sport('alpine_skiing'), True),
    'DUATHLON': (None, False),
    'DUATHLON_CYCLING': (Sport('cycling'), False),
    'DUATHLON_RUNNING': (Sport('running'), False),
    'ESPORTS': (None, False),
    'E_BIKE': (Sport('cycling+assisted'), True),
    'FIELD_HOCKEY': (None, False),
    'FINNISH_BASEBALL': (None, False),
    'FITNESS_BOXING': (None, False),
    'FITNESS_DANCING': (None, False),
    'FITNESS_MARTIAL_ARTS': (None, False),
    'FITNESS_RACING': (None, False),
    'FITNESS_STEP': (None, False),
    'FLOORBALL': (None, False),
    'FREE_MULTISPORT': (None, False),
    'FRISBEEGOLF': (None, False),
    'FUNCTIONAL_TRAINING': (None, False),
    'FUTSAL': (None, False),
    'GOLF': (None, False),
    'GRAVEL': (Sport('cycling.gravel'), True),
    'GROUP_EXERCISE': (None, False),
    'GYMNASTICK': (None, False),
    'HANDBALL': (None, False),
    'HIIT': (None, False),
    'HIKING': (Sport('walking.hiking'), True),
    'ICE_HOCKEY': (None, False),
    'ICE_SKATING': (None, False),
    'INDOOR_CYCLING': (Sport('cycling+stationary'), True),
    'INDOOR_ROWING': (Sport('rowing+stationary'), True),
    'INLINE_SKATING': (None, False),
    'JAZZ_DANCING': (None, False),
    'JOGGING': (Sport('running'), False),
    'JUDO_MARTIAL_ARTS': (None, False),
    'JUMP_ROPE': (None, False),
    'KETTLEBELL': (None, False),
    'KICKBIKE': (None, False),
    'KICKBOXING_MARTIAL_ARTS': (None, False),
    'LATIN_DANCING': (None, False),
    'LES_MILLS_BARRE': (None, False),
    'LES_MILLS_BODYATTACK': (None, False),
    'LES_MILLS_BODYBALANCE': (None, False),
    'LES_MILLS_BODYCOMBAT': (None, False),
    'LES_MILLS_BODYJAM': (None, False),
    'LES_MILLS_BODYPUMP': (None, False),
    'LES_MILLS_BODYSTEP': (None, False),
    'LES_MILLS_CXWORKS': (None, False),
    'LES_MILLS_GRIT_ATHLETIC': (None, False),
    'LES_MILLS_GRIT_CARDIO': (None, False),
    'LES_MILLS_GRIT_STRENGTH': (None, False),
    'LES_MILLS_RPM': (None, False),
    'LES_MILLS_SHBAM': (None, False),
    'LES_MILLS_SPRINT': (None, False),
    'LES_MILLS_TONE': (None, False),
    'LES_MILLS_TRIP': (None, False),
    'MOBILITY_DYNAMIC': (None, False),
    'MOBILITY_STATIC': (None, False),
    'MODERN_DANCING': (None, False),
    'MOTORSPORTS_CAR_RACING': (None, False),
    'MOTORSPORTS_ENDURO': (None, False),
    'MOTORSPORTS_HARD_ENDURO': (None, False),
    'MOTORSPORTS_MOTOCROSS': (None, False),
    'MOTORSPORTS_ROADRACING': (None, False),
    'MOTORSPORTS_SNOCROSS': (None, False),
    'MOUNTAIN_BIKING': (Sport('cycling.mountain'), True),
    'NORDIC_WALKING': (Sport('walking'), False),
    'OBSTACLE_COURSE_RACING': (None, False),
    'OFFROADDUATHLON': (None, False),
    'OFFROADDUATHLON_CYCLING': (Sport('cycling.mountain'), False),
    'OFFROADDUATHLON_RUNNING': (Sport('running.trail'), False),
    'OFFROADTRIATHLON': (None, False),
    'OFFROADTRIATHLON_CYCLING': (Sport('cycling.mountain'), False),
    'OFFROADTRIATHLON_RUNNING': (Sport('running.trail'), False),
    'OFFROADTRIATHLON_SWIMMING': (Sport('swimming.open_water'), False),
    'OPEN_WATER_SWIMMING': (Sport('swimming.open_water'), True),
    'ORIENTEERING': (None, False),
    'ORIENTEERING_MTB': (Sport('cycling.mountain'), False),
    'ORIENTEERING_SKI': (Sport('xc_skiing'), False),
    'OTHER_INDOOR': (Sport('generic'), False),
    'OTHER_OUTDOOR': (Sport('generic'), True),
    'PADEL': (None, False),
    'PARASPORTS_HAND_CYCLING': (Sport('hand_cycling'), True),
    'PARASPORTS_SLED_HOCKEY': (None, False),
    'PARASPORTS_WATER_SKIING': (None, False),
    'PARASPORTS_WHEELCHAIR': (None, False),
    'PARASPORTS_WHEELCHAIR_BASKETBALL': (None, False),
    'PARASPORTS_WHEELCHAIR_TENNIS': (None, False),
    'PICKLEBALL': (None, False),
    'PILATES': (None, False),
    'POOL_SWIMMING': (Sport('swimming.pool'), True),
    'RIDING': (None, False),
    'RINGETTE': (None, False),
    'ROAD_BIKING': (Sport('cycling.road'), True),
    'ROAD_RUNNING': (Sport('running.road'), True),
    'ROLLER_BLADING': (None, False),
    'ROLLER_SKIING_CLASSIC': (Sport('xc_skiing.classic+roller'), True),
    'ROLLER_SKIING_FREESTYLE': (Sport('xc_skiing.skate+roller'), True),
    'ROWING': (Sport('rowing'), True),
    'RUCKING': (Sport('walking'), False),
    'RUGBY': (None, False),
    'RUNNING': (Sport('running'), True),
    'SHOOTING_SPORT_INDOOR': (None, False),
    'SHOOTING_SPORT_OUTDOOR': (None, False),
    'SHOW_DANCING': (None, False),
    'SKATEBOARDING': (None, False),
    'SKATING': (None, False),
    'SKIERG': (None, False),
    'SNOWBOARDING': (Sport('snowboarding'), True),
    'SNOWSHOE_TREKKING': (None, False),
    'SOCCER': (None, False),
    'SPINNING': (Sport('cycling+stationary'), False),
    'SQUASH': (None, False),
    'STAIR_WORKOUT': (None, False),
    'STREET_DANCING': (None, False),
    'STRENGTH_TRAINING': (None, False),
    'STRETCHING': (None, False),
    'SUP': (None, False),
    'SWIMMING': (Sport('swimming'), True),
    'TABLE_TENNIS': (None, False),
    'TAEKWONDO_MARTIAL_ARTS': (None, False),
    'TELEMARK_SKIING': (Sport('alpine_skiing'), False),
    'TENNIS': (None, False),
    'TRACK_AND_FIELD_RUNNING': (Sport('running.track'), True),
    'TRAIL_RUNNING': (Sport('running.trail'), True),
    'TREADMILL_RUNNING': (Sport('running+stationary'), True),
    'TRIATHLON': (None, False),
    'TRIATHLON_CYCLING': (Sport('cycling'), False),
    'TRIATHLON_RUNNING': (Sport('running'), False),
    'TRIATHLON_SWIMMING': (Sport('swimming.open_water'), False),
    'TROTTING': (None, False),
    'ULTIMATE': (None, False),
    'ULTRARUNNING_RUNNING': (Sport('running'), False),
    'VERTICALSPORTS_OUTCLIMBING': (None, False),
    'VERTICALSPORTS_WALLCLIMBING': (None, False),
    'VOLLEYBALL': (None, False),
    'WALKING': (Sport('walking'), True),
    'WATERSPORTS_CANOEING': (None, False),
    'WATERSPORTS_KAYAKING': (None, False),
    'WATERSPORTS_KITESURFING': (None, False),
    'WATERSPORTS_SAILING': (None, False),
    'WATERSPORTS_SURFING': (None, False),
    'WATERSPORTS_WAKEBOARDING': (None, False),
    'WATERSPORTS_WATERSKI': (None, False),
    'WATERSPORTS_WINDSURFING': (None, False),
    'WATER_EXERCISE': (None, False),
    'WATER_RUNNING': (None, False),
    'XC_SKIING_CLASSIC': (Sport('xc_skiing.classic'), True),
    'XC_SKIING_FREESTYLE': (Sport('xc_skiing.skate'), True),
    'YOGA': (None, False),
}

POLAR_PREFERRED_INDEX: dict = {
    ('xc_skiing', frozenset()): 'CROSS-COUNTRY_SKIING',
    ('cycling', frozenset()): 'CYCLING',
    ('alpine_skiing', frozenset()): 'DOWNHILL_SKIING',
    ('cycling', frozenset({'assisted'})): 'E_BIKE',
    ('cycling.gravel', frozenset()): 'GRAVEL',
    ('walking.hiking', frozenset()): 'HIKING',
    ('cycling', frozenset({'stationary'})): 'INDOOR_CYCLING',
    ('rowing', frozenset({'stationary'})): 'INDOOR_ROWING',
    ('cycling.mountain', frozenset()): 'MOUNTAIN_BIKING',
    ('swimming.open_water', frozenset()): 'OPEN_WATER_SWIMMING',
    ('generic', frozenset()): 'OTHER_OUTDOOR',
    ('hand_cycling', frozenset()): 'PARASPORTS_HAND_CYCLING',
    ('swimming.pool', frozenset()): 'POOL_SWIMMING',
    ('cycling.road', frozenset()): 'ROAD_BIKING',
    ('running.road', frozenset()): 'ROAD_RUNNING',
    ('xc_skiing.classic', frozenset({'roller'})): 'ROLLER_SKIING_CLASSIC',
    ('xc_skiing.skate', frozenset({'roller'})): 'ROLLER_SKIING_FREESTYLE',
    ('rowing', frozenset()): 'ROWING',
    ('running', frozenset()): 'RUNNING',
    ('snowboarding', frozenset()): 'SNOWBOARDING',
    ('swimming', frozenset()): 'SWIMMING',
    ('running.track', frozenset()): 'TRACK_AND_FIELD_RUNNING',
    ('running.trail', frozenset()): 'TRAIL_RUNNING',
    ('running', frozenset({'stationary'})): 'TREADMILL_RUNNING',
    ('walking', frozenset()): 'WALKING',
    ('xc_skiing.classic', frozenset()): 'XC_SKIING_CLASSIC',
    ('xc_skiing.skate', frozenset()): 'XC_SKIING_FREESTYLE',
}

POLAR_TARGET_COARSENING: tuple = ()

# ---- strava --------------------------------------------------------------

STRAVA_FALLBACK_ENCODE = 'Workout'
STRAVA_FALLBACK_DECODE: Sport = Sport('generic')

STRAVA_ENTRIES_BY_TARGET: dict = {
    'AlpineSki': (Sport('alpine_skiing'), True),
    'BackcountrySki': (Sport('alpine_skiing'), False),
    'Badminton': (None, False),
    'Basketball': (None, False),
    'Canoeing': (None, False),
    'Cricket': (None, False),
    'Crossfit': (None, False),
    'Dance': (None, False),
    'EBikeRide': (Sport('cycling+assisted'), True),
    'EMountainBikeRide': (Sport('cycling.mountain+assisted'), True),
    'Elliptical': (None, False),
    'Golf': (None, False),
    'GravelRide': (Sport('cycling.gravel'), True),
    'Handcycle': (Sport('hand_cycling'), True),
    'HighIntensityIntervalTraining': (None, False),
    'Hike': (Sport('walking.hiking'), True),
    'IceSkate': (None, False),
    'InlineSkate': (None, False),
    'Kayaking': (None, False),
    'Kitesurf': (None, False),
    'MountainBikeRide': (Sport('cycling.mountain'), True),
    'NordicSki': (Sport('xc_skiing'), True),
    'Padel': (None, False),
    'PhysicalTherapy': (None, False),
    'Pickleball': (None, False),
    'Pilates': (None, False),
    'Racquetball': (None, False),
    'Ride': (Sport('cycling'), True),
    'RockClimbing': (None, False),
    'RollerSki': (Sport('xc_skiing+roller'), True),
    'Rowing': (Sport('rowing'), True),
    'Run': (Sport('running'), True),
    'Sail': (None, False),
    'Skateboard': (None, False),
    'Snowboard': (Sport('snowboarding'), True),
    'Snowshoe': (None, False),
    'Soccer': (None, False),
    'Squash': (None, False),
    'StairStepper': (None, False),
    'StandUpPaddling': (None, False),
    'Surfing': (None, False),
    'Swim': (Sport('swimming'), True),
    'TableTennis': (None, False),
    'Tennis': (None, False),
    'TrailRun': (Sport('running.trail'), True),
    'Velomobile': (None, False),
    'VirtualRide': (Sport('cycling+stationary+virtual'), True),
    'VirtualRow': (Sport('rowing+stationary+virtual'), True),
    'VirtualRun': (Sport('running+stationary+virtual'), True),
    'Volleyball': (None, False),
    'Walk': (Sport('walking'), True),
    'WeightTraining': (None, False),
    'Wheelchair': (None, False),
    'Windsurf': (None, False),
    'Workout': (Sport('generic'), True),
    'Yoga': (None, False),
}

STRAVA_PREFERRED_INDEX: dict = {
    ('alpine_skiing', frozenset()): 'AlpineSki',
    ('cycling', frozenset({'assisted'})): 'EBikeRide',
    ('cycling.mountain', frozenset({'assisted'})): 'EMountainBikeRide',
    ('cycling.gravel', frozenset()): 'GravelRide',
    ('hand_cycling', frozenset()): 'Handcycle',
    ('walking.hiking', frozenset()): 'Hike',
    ('cycling.mountain', frozenset()): 'MountainBikeRide',
    ('xc_skiing', frozenset()): 'NordicSki',
    ('cycling', frozenset()): 'Ride',
    ('xc_skiing', frozenset({'roller'})): 'RollerSki',
    ('rowing', frozenset()): 'Rowing',
    ('running', frozenset()): 'Run',
    ('snowboarding', frozenset()): 'Snowboard',
    ('swimming', frozenset()): 'Swim',
    ('running.trail', frozenset()): 'TrailRun',
    ('cycling', frozenset({'stationary', 'virtual'})): 'VirtualRide',
    ('rowing', frozenset({'stationary', 'virtual'})): 'VirtualRow',
    ('running', frozenset({'stationary', 'virtual'})): 'VirtualRun',
    ('walking', frozenset()): 'Walk',
    ('generic', frozenset()): 'Workout',
}

STRAVA_TARGET_COARSENING: tuple = ()

# ---- suunto --------------------------------------------------------------

SUUNTO_FALLBACK_ENCODE = 4
SUUNTO_FALLBACK_DECODE: Sport = Sport('generic')

SUUNTO_ENTRIES_BY_TARGET: dict = {
    0: (Sport('walking'), True),
    1: (Sport('running'), True),
    2: (Sport('cycling'), True),
    3: (Sport('xc_skiing'), True),
    4: (Sport('generic'), True),
    5: (Sport('generic'), False),
    6: (Sport('generic'), False),
    7: (Sport('generic'), False),
    8: (Sport('generic'), False),
    9: (Sport('generic'), False),
    10: (Sport('cycling.mountain'), True),
    11: (Sport('walking.hiking'), True),
    12: (None, False),
    13: (Sport('alpine_skiing'), True),
    14: (None, False),
    15: (Sport('rowing'), True),
    16: (None, False),
    17: (None, False),
    18: (None, False),
    19: (None, False),
    20: (None, False),
    21: (Sport('swimming'), True),
    22: (Sport('running.trail'), True),
    23: (None, False),
    24: (Sport('walking'), False),
    25: (None, False),
    26: (None, False),
    27: (None, False),
    28: (None, False),
    29: (None, False),
    30: (Sport('snowboarding'), True),
    31: (None, False),
    32: (None, False),
    33: (None, False),
    34: (None, False),
    35: (None, False),
    36: (None, False),
    37: (None, False),
    38: (None, False),
    39: (None, False),
    40: (None, False),
    41: (None, False),
    42: (None, False),
    43: (None, False),
    44: (None, False),
    45: (None, False),
    46: (None, False),
    47: (None, False),
    48: (None, False),
    49: (None, False),
    50: (None, False),
    51: (None, False),
    52: (Sport('cycling+stationary'), True),
    53: (Sport('running+stationary'), True),
    54: (None, False),
    55: (None, False),
    56: (Sport('xc_skiing+roller'), True),
    57: (Sport('rowing+stationary'), True),
    58: (None, False),
    59: (Sport('running.track'), True),
    60: (None, False),
    61: (None, False),
    62: (None, False),
    63: (None, False),
    64: (None, False),
    65: (None, False),
    66: (None, False),
    67: (None, False),
    68: (None, False),
    69: (None, False),
    70: (Sport('walking.hiking'), False),
    71: (None, False),
    72: (None, False),
    73: (None, False),
    74: (None, False),
    75: (None, False),
    76: (None, False),
    77: (None, False),
    78: (None, False),
    79: (None, False),
    80: (None, False),
    81: (None, False),
    82: (None, False),
    83: (None, False),
    84: (Sport('alpine_skiing'), False),
    85: (Sport('swimming.open_water'), True),
    86: (None, False),
    87: (None, False),
    88: (None, False),
    90: (None, False),
    91: (None, False),
    92: (None, False),
    93: (None, False),
    94: (None, False),
    95: (None, False),
    96: (None, False),
    97: (None, False),
    98: (None, False),
    99: (Sport('cycling.gravel'), True),
    100: (None, False),
    101: (None, False),
    102: (None, False),
    103: (Sport('running.track'), False),
    104: (None, False),
    105: (Sport('cycling+assisted'), True),
    106: (Sport('cycling.mountain+assisted'), True),
    107: (Sport('alpine_skiing'), False),
    108: (None, False),
    109: (Sport('hand_cycling'), True),
    110: (Sport('snowboarding'), False),
    111: (None, False),
    112: (None, False),
    113: (None, False),
    114: (Sport('cycling.cyclocross'), True),
    115: (Sport('running.trail'), False),
    116: (None, False),
    117: (Sport('xc_skiing.skate'), True),
    118: (Sport('xc_skiing.classic'), True),
    119: (None, False),
    120: (None, False),
    121: (None, False),
}

SUUNTO_PREFERRED_INDEX: dict = {
    ('walking', frozenset()): 0,
    ('running', frozenset()): 1,
    ('cycling', frozenset()): 2,
    ('xc_skiing', frozenset()): 3,
    ('generic', frozenset()): 4,
    ('cycling.mountain', frozenset()): 10,
    ('walking.hiking', frozenset()): 11,
    ('alpine_skiing', frozenset()): 13,
    ('rowing', frozenset()): 15,
    ('swimming', frozenset()): 21,
    ('running.trail', frozenset()): 22,
    ('snowboarding', frozenset()): 30,
    ('cycling', frozenset({'stationary'})): 52,
    ('running', frozenset({'stationary'})): 53,
    ('xc_skiing', frozenset({'roller'})): 56,
    ('rowing', frozenset({'stationary'})): 57,
    ('running.track', frozenset()): 59,
    ('swimming.open_water', frozenset()): 85,
    ('cycling.gravel', frozenset()): 99,
    ('cycling', frozenset({'assisted'})): 105,
    ('cycling.mountain', frozenset({'assisted'})): 106,
    ('hand_cycling', frozenset()): 109,
    ('cycling.cyclocross', frozenset()): 114,
    ('xc_skiing.skate', frozenset()): 117,
    ('xc_skiing.classic', frozenset()): 118,
}

SUUNTO_TARGET_COARSENING: tuple = ()

# ---- wahoo ---------------------------------------------------------------

WAHOO_FALLBACK_ENCODE = 47
WAHOO_FALLBACK_DECODE: Sport = Sport('generic')

WAHOO_ENTRIES_BY_TARGET: dict = {
    0: (Sport('cycling'), True),
    1: (Sport('running'), True),
    2: (Sport('generic'), False),
    3: (Sport('running.track'), True),
    4: (Sport('running.trail'), True),
    5: (Sport('running+stationary'), True),
    6: (Sport('walking'), True),
    7: (Sport('walking'), False),
    8: (Sport('walking'), False),
    9: (Sport('walking.hiking'), True),
    10: (None, False),
    11: (Sport('cycling.cyclocross'), True),
    12: (Sport('cycling+stationary'), True),
    13: (Sport('cycling.mountain'), True),
    14: (Sport('cycling'), False),
    15: (Sport('cycling.road'), True),
    16: (Sport('cycling.track'), True),
    17: (None, False),
    18: (Sport('generic'), False),
    19: (Sport('running+stationary'), False),
    20: (None, False),
    21: (Sport('cycling+stationary'), False),
    22: (Sport('rowing+stationary'), True),
    23: (None, False),
    25: (Sport('swimming.pool'), True),
    26: (Sport('swimming.open_water'), True),
    27: (Sport('snowboarding'), True),
    28: (Sport('alpine_skiing'), False),
    29: (Sport('alpine_skiing'), True),
    30: (Sport('xc_skiing'), True),
    31: (None, False),
    32: (None, False),
    33: (None, False),
    34: (None, False),
    35: (None, False),
    36: (None, False),
    37: (None, False),
    38: (None, False),
    39: (Sport('rowing'), True),
    40: (None, False),
    41: (None, False),
    42: (Sport('generic'), False),
    43: (None, False),
    44: (None, False),
    45: (None, False),
    46: (None, False),
    47: (Sport('generic'), True),
    49: (Sport('cycling+stationary'), False),
    56: (Sport('walking+stationary'), True),
    61: (Sport('cycling+stationary'), False),
    62: (None, False),
    63: (None, False),
    64: (Sport('cycling+assisted'), True),
    65: (Sport('generic'), False),
    66: (None, False),
    67: (Sport('running+race'), True),
    68: (Sport('cycling+stationary+virtual'), True),
    69: (None, False),
    70: (Sport('hand_cycling'), True),
    71: (Sport('running+stationary+virtual'), True),
    255: (Sport('generic'), False),
}

WAHOO_PREFERRED_INDEX: dict = {
    ('cycling', frozenset()): 0,
    ('running', frozenset()): 1,
    ('running.track', frozenset()): 3,
    ('running.trail', frozenset()): 4,
    ('running', frozenset({'stationary'})): 5,
    ('walking', frozenset()): 6,
    ('walking.hiking', frozenset()): 9,
    ('cycling.cyclocross', frozenset()): 11,
    ('cycling', frozenset({'stationary'})): 12,
    ('cycling.mountain', frozenset()): 13,
    ('cycling.road', frozenset()): 15,
    ('cycling.track', frozenset()): 16,
    ('rowing', frozenset({'stationary'})): 22,
    ('swimming.pool', frozenset()): 25,
    ('swimming.open_water', frozenset()): 26,
    ('snowboarding', frozenset()): 27,
    ('alpine_skiing', frozenset()): 29,
    ('xc_skiing', frozenset()): 30,
    ('rowing', frozenset()): 39,
    ('generic', frozenset()): 47,
    ('walking', frozenset({'stationary'})): 56,
    ('cycling', frozenset({'assisted'})): 64,
    ('running', frozenset({'race'})): 67,
    ('cycling', frozenset({'stationary', 'virtual'})): 68,
    ('hand_cycling', frozenset()): 70,
    ('running', frozenset({'stationary', 'virtual'})): 71,
}

WAHOO_TARGET_COARSENING: tuple = ()

# ---- FIT enum reference tables -------------------------------------------

FIT_SPORT_IDS: dict[str, int] = {
    "generic": 0,
    "running": 1,
    "cycling": 2,
    "transition": 3,
    "fitness_equipment": 4,
    "swimming": 5,
    "basketball": 6,
    "soccer": 7,
    "tennis": 8,
    "american_football": 9,
    "training": 10,
    "walking": 11,
    "cross_country_skiing": 12,
    "alpine_skiing": 13,
    "snowboarding": 14,
    "rowing": 15,
    "mountaineering": 16,
    "hiking": 17,
    "multisport": 18,
    "paddling": 19,
    "flying": 20,
    "e_biking": 21,
    "motorcycling": 22,
    "boating": 23,
    "driving": 24,
    "golf": 25,
    "hang_gliding": 26,
    "horseback_riding": 27,
    "hunting": 28,
    "fishing": 29,
    "inline_skating": 30,
    "rock_climbing": 31,
    "sailing": 32,
    "ice_skating": 33,
    "sky_diving": 34,
    "snowshoeing": 35,
    "snowmobiling": 36,
    "stand_up_paddleboarding": 37,
    "surfing": 38,
    "wakeboarding": 39,
    "water_skiing": 40,
    "kayaking": 41,
    "rafting": 42,
    "windsurfing": 43,
    "kitesurfing": 44,
    "tactical": 45,
    "jumpmaster": 46,
    "boxing": 47,
    "floor_climbing": 48,
    "baseball": 49,
    "diving": 53,
    "hiit": 62,
    "racket": 64,
    "wheelchair_push_walk": 65,
    "wheelchair_push_run": 66,
    "meditation": 67,
    "disc_golf": 69,
    "cricket": 71,
    "rugby": 72,
    "hockey": 73,
    "lacrosse": 74,
    "volleyball": 75,
    "water_tubing": 76,
    "wakesurfing": 77,
    "mixed_martial_arts": 80,
    "snorkeling": 82,
    "dance": 83,
    "jump_rope": 84,
    "all": 254,
}

FIT_SPORT_NAMES: dict[int, str] = {v: k for k, v in FIT_SPORT_IDS.items()}

FIT_SUB_SPORT_IDS: dict[str, int] = {
    "generic": 0,
    "treadmill": 1,
    "street": 2,
    "trail": 3,
    "track": 4,
    "spin": 5,
    "indoor_cycling": 6,
    "road": 7,
    "mountain": 8,
    "downhill": 9,
    "recumbent": 10,
    "cyclocross": 11,
    "hand_cycling": 12,
    "track_cycling": 13,
    "indoor_rowing": 14,
    "elliptical": 15,
    "stair_climbing": 16,
    "lap_swimming": 17,
    "open_water": 18,
    "flexibility_training": 19,
    "strength_training": 20,
    "warm_up": 21,
    "match": 22,
    "exercise": 23,
    "challenge": 24,
    "indoor_skiing": 25,
    "cardio_training": 26,
    "indoor_walking": 27,
    "e_bike_fitness": 28,
    "bmx": 29,
    "casual_walking": 30,
    "speed_walking": 31,
    "bike_to_run_transition": 32,
    "run_to_bike_transition": 33,
    "swim_to_bike_transition": 34,
    "atv": 35,
    "motocross": 36,
    "backcountry": 37,
    "resort": 38,
    "rc_drone": 39,
    "wingsuit": 40,
    "whitewater": 41,
    "skate_skiing": 42,
    "yoga": 43,
    "pilates": 44,
    "indoor_running": 45,
    "gravel_cycling": 46,
    "e_bike_mountain": 47,
    "commuting": 48,
    "mixed_surface": 49,
    "navigate": 50,
    "track_me": 51,
    "map": 52,
    "single_gas_diving": 53,
    "multi_gas_diving": 54,
    "gauge_diving": 55,
    "apnea_diving": 56,
    "apnea_hunting": 57,
    "virtual_activity": 58,
    "obstacle": 59,
    "breathing": 62,
    "sail_race": 65,
    "ultra": 67,
    "indoor_climbing": 68,
    "bouldering": 69,
    "hiit": 70,
    "amrap": 73,
    "emom": 74,
    "tabata": 75,
    "pickleball": 84,
    "padel": 85,
    "indoor_wheelchair_walk": 86,
    "indoor_wheelchair_run": 87,
    "indoor_hand_cycling": 88,
    "squash": 94,
    "badminton": 95,
    "racquetball": 96,
    "table_tennis": 97,
    "fly_canopy": 110,
    "fly_paraglide": 111,
    "fly_paramotor": 112,
    "fly_pressurized": 113,
    "fly_navigate": 114,
    "fly_timer": 115,
    "fly_altimeter": 116,
    "fly_wx": 117,
    "fly_vfr": 118,
    "fly_ifr": 119,
    "all": 254,
}

FIT_SUB_SPORT_NAMES: dict[int, str] = {v: k for k, v in FIT_SUB_SPORT_IDS.items()}
