# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///

"""Build reference/apple-healthkit/targets.yaml from workout_activity_types.yaml.

Apple HealthKit's HKWorkoutActivityType is a flat integer enum. Every
`raw_value` is a legal target.

Run:
    uv run scripts/build_reference/apple_healthkit.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
REF_DIR = ROOT / "reference" / "apple-healthkit"
SOURCE_PATH = REF_DIR / "workout_activity_types.yaml"
TARGETS_PATH = REF_DIR / "targets.yaml"


def main() -> int:
    source = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    cases = source["cases"]
    targets = sorted((c["raw_value"], c["name"]) for c in cases)

    lines = [
        "# Apple HealthKit — legal HKWorkoutActivityType target enumeration.",
        "#",
        "# Generated by scripts/build_reference/apple_healthkit.py from",
        "# workout_activity_types.yaml. Do not edit by hand.",
        "",
        "targets:",
    ]
    for raw_value, name in targets:
        lines.append(f"  - {raw_value:>4}  # {name}")
    lines.append("")

    TARGETS_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGETS_PATH.relative_to(ROOT)}: {len(targets)} targets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
