# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///

"""Build reference/garmin-fit-sdk/targets.yaml from the FIT SDK enums.

A target is a legal `(sport, sub_sport)` pair under the FIT protocol.
The rule:

  - For every sport id, `(sport_id, 0)` is legal (the `generic` sub_sport
    is universally applicable).
  - For every sub_sport, `(sport_id, sub_sport_id)` is legal when the
    sub_sport's `associated_sports` list contains the sport's name.
  - The `all = 254` sentinel exists in both enums for SDK queries; it
    is not a recordable activity type and is excluded.

Run:
    uv run scripts/build_reference/garmin_fit.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
REF_DIR = ROOT / "reference" / "garmin-fit-sdk"
SPORTS_PATH = REF_DIR / "sports.yaml"
SUB_SPORTS_PATH = REF_DIR / "sub_sports.yaml"
TARGETS_PATH = REF_DIR / "targets.yaml"

ALL_SENTINEL = 254

# Sub_sports the FIT SDK leaves unassociated for a given sport (no entry in
# `associated_sports`) but that real devices and virtual platforms do emit
# under that sport. The FIT protocol permits any (sport, sub_sport) pair;
# targets.yaml is the curated set OST commits to mapping, so these are
# enumerated explicitly rather than fabricated as SDK associations.
#   virtual_activity (58): empty SDK comment, but Zwift and similar write
#   running/virtual_activity and cycling/virtual_activity.
#   indoor_rowing (14): SDK comment is "Fitness Equipment" only, but Garmin
#   watches with a dedicated indoor-row profile write rowing/indoor_rowing.
OBSERVED_TARGETS: list[tuple[str, int]] = [
    ("running", 58),  # virtual_activity
    ("cycling", 58),  # virtual_activity
    ("rowing", 14),  # indoor_rowing
]


def build_targets() -> list[dict]:
    sports = yaml.safe_load(SPORTS_PATH.read_text(encoding="utf-8"))["cases"]
    sub_sports = yaml.safe_load(SUB_SPORTS_PATH.read_text(encoding="utf-8"))["cases"]

    sport_id_to_name = {s["value"]: s["name"] for s in sports if s["value"] != ALL_SENTINEL}
    targets: list[tuple[int, int]] = []

    # Generic sub_sport (0) is legal under every sport.
    for sport_id in sorted(sport_id_to_name):
        targets.append((sport_id, 0))

    # Each non-generic sub_sport is legal under each sport in its
    # `associated_sports` list. Sub_sports without `associated_sports`
    # are skipped here; they only appear as `(sport_id, 0)` is generic.
    for ss in sub_sports:
        if ss["value"] in (0, ALL_SENTINEL):
            continue
        for sport_name in ss.get("associated_sports", []):
            # Look up the sport id by name.
            for sport_id, name in sport_id_to_name.items():
                if name == sport_name:
                    targets.append((sport_id, ss["value"]))
                    break

    # Curated pairs the SDK does not associate but devices/platforms emit.
    name_to_sport_id = {name: sid for sid, name in sport_id_to_name.items()}
    for sport_name, ss_value in OBSERVED_TARGETS:
        sport_id = name_to_sport_id.get(sport_name)
        if sport_id is not None:
            targets.append((sport_id, ss_value))

    # Deduplicate and sort.
    targets = sorted(set(targets))
    return [{"sport": s, "sub_sport": ss} for s, ss in targets]


def render(
    targets: list[dict], sport_names: dict[int, str], sub_sport_names: dict[int, str]
) -> str:
    lines = [
        "# Garmin FIT SDK — legal (sport, sub_sport) target enumeration.",
        "#",
        "# Generated by scripts/build_reference/garmin_fit.py from sports.yaml",
        "# and sub_sports.yaml. Do not edit by hand.",
        "#",
        "# Each target is a legal pair the FIT protocol permits in a session",
        "# `sport`/`sub_sport` field. Used by the format v3 loader (validation",
        "# rules 5 and 6 in docs/translation.md) to enforce structural coverage",
        "# of mappings/garmin_fit.yaml.",
        "",
        "targets:",
    ]
    for t in targets:
        s, ss = t["sport"], t["sub_sport"]
        s_name = sport_names.get(s, "?")
        ss_name = sub_sport_names.get(ss, "?")
        lines.append(f"  - {{ sport: {s:>3}, sub_sport: {ss:>3} }}  # {s_name} / {ss_name}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    sports = yaml.safe_load(SPORTS_PATH.read_text(encoding="utf-8"))["cases"]
    sub_sports = yaml.safe_load(SUB_SPORTS_PATH.read_text(encoding="utf-8"))["cases"]
    sport_names = {s["value"]: s["name"] for s in sports}
    sub_sport_names = {ss["value"]: ss["name"] for ss in sub_sports}

    targets = build_targets()
    text = render(targets, sport_names, sub_sport_names)
    TARGETS_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {TARGETS_PATH.relative_to(ROOT)}: {len(targets)} targets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
