# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///

"""Build reference/garmin-training-api/targets.yaml.

The Garmin Training API V2 sport-type enum is small (9 values) and not
distributed as a machine-readable file — the upstream PDF is confidential
under the Garmin Connect Developer Program agreement. The enum is
transcribed directly from the README.

Run:
    uv run scripts/build_reference/garmin_training_api.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
REF_DIR = ROOT / "reference" / "garmin-training-api"
TARGETS_PATH = REF_DIR / "targets.yaml"

# Source: Training API V2 spec, README.md.
TARGETS = [
    "CARDIO_TRAINING",
    "CYCLING",
    "GENERIC",
    "LAP_SWIMMING",
    "MULTI_SPORT",
    "PILATES",
    "RUNNING",
    "STRENGTH_TRAINING",
    "YOGA",
]


def main() -> int:
    lines = [
        "# Garmin Training API V2 — legal sport-type target enumeration.",
        "#",
        "# Generated by scripts/build_reference/garmin_training_api.py.",
        "# The upstream spec is not redistributable; values are transcribed",
        "# from the public README into the build script. Do not edit by hand.",
        "",
        "targets:",
    ]
    for t in TARGETS:
        lines.append(f"  - {t}")
    lines.append("")

    TARGETS_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGETS_PATH.relative_to(ROOT)}: {len(TARGETS)} targets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
