# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///

"""Build reference/polar/targets.yaml from detailed_sport_info.yaml.

Polar AccessLink's detailed_sport_info is a flat string enum. Every `value`
is a legal target. `flow_label` is the human-readable Polar Flow name, used
for comments only.

Run:
    uv run scripts/build_reference/polar.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
REF_DIR = ROOT / "reference" / "polar"
SOURCE_PATH = REF_DIR / "detailed_sport_info.yaml"
TARGETS_PATH = REF_DIR / "targets.yaml"


def main() -> int:
    source = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    cases = source["cases"]
    targets = sorted((c["value"], c["flow_label"]) for c in cases)

    lines = [
        "# Polar AccessLink — legal detailed_sport_info target enumeration.",
        "#",
        "# Generated by scripts/build_reference/polar.py from",
        "# detailed_sport_info.yaml. Do not edit by hand.",
        "",
        "targets:",
    ]
    for value, flow_label in targets:
        lines.append(f"  - {value}  # {flow_label}")
    lines.append("")

    TARGETS_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGETS_PATH.relative_to(ROOT)}: {len(targets)} targets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
