# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///

"""Build reference/strava/targets.yaml from sport_types.yaml.

Strava's SportType enum is a flat string list. Every value is a legal
target with no associations or hierarchy.

Run:
    uv run scripts/build_reference/strava.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
REF_DIR = ROOT / "reference" / "strava"
SOURCE_PATH = REF_DIR / "sport_types.yaml"
TARGETS_PATH = REF_DIR / "targets.yaml"


def main() -> int:
    source = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    targets = sorted(source["cases"])

    lines = [
        "# Strava — legal SportType target enumeration.",
        "#",
        "# Generated by scripts/build_reference/strava.py from sport_types.yaml.",
        "# Do not edit by hand.",
        "",
        "targets:",
    ]
    for t in targets:
        lines.append(f"  - {t}")
    lines.append("")

    TARGETS_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGETS_PATH.relative_to(ROOT)}: {len(targets)} targets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
