# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///

"""Build reference/suunto/targets.yaml from activities.yaml.

Suunto's activity ID is a flat integer enum (with gaps; ID 89 is unassigned).
Every `value` is a legal target. `name` is the activity label, used for
comments only.

Run:
    uv run scripts/build_reference/suunto.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
REF_DIR = ROOT / "reference" / "suunto"
SOURCE_PATH = REF_DIR / "activities.yaml"
TARGETS_PATH = REF_DIR / "targets.yaml"


def main() -> int:
    source = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    cases = source["cases"]
    targets = sorted((c["value"], c["name"]) for c in cases)

    lines = [
        "# Suunto — legal activity-ID target enumeration.",
        "#",
        "# Generated by scripts/build_reference/suunto.py from activities.yaml.",
        "# Do not edit by hand.",
        "",
        "targets:",
    ]
    for value, name in targets:
        lines.append(f"  - {value:>4}  # {name}")
    lines.append("")

    TARGETS_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGETS_PATH.relative_to(ROOT)}: {len(targets)} targets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
