# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///

"""Build reference/wahoo/targets.yaml from workout_types.yaml.

Wahoo's workout_type_id is a flat integer enum. Every `value` is a legal
target. `family` and `location` are derived attributes (used for review and
mapping comments), not part of the target.

Run:
    uv run scripts/build_reference/wahoo.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
REF_DIR = ROOT / "reference" / "wahoo"
SOURCE_PATH = REF_DIR / "workout_types.yaml"
TARGETS_PATH = REF_DIR / "targets.yaml"


def main() -> int:
    source = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    cases = source["cases"]
    targets = sorted((c["value"], c["name"]) for c in cases)

    lines = [
        "# Wahoo Cloud API — legal workout_type_id target enumeration.",
        "#",
        "# Generated by scripts/build_reference/wahoo.py from",
        "# workout_types.yaml. Do not edit by hand.",
        "",
        "targets:",
    ]
    for value, name in targets:
        lines.append(f"  - {value:>4}  # {name}")
    lines.append("")

    TARGETS_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGETS_PATH.relative_to(ROOT)}: {len(targets)} targets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
